
time="2025-07-30T17:42:51-03:00" level=warning msg="/home/rinha-user/rinha-de-backend-2025/participantes/Maxel-Uds-quarkus/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network maxel-uds-quarkus_payment-router  Creating
 Network maxel-uds-quarkus_payment-router  Created
 Container postgres  Creating
 Container postgres  Created
 Container api2  Creating
 Container api1  Creating
 Container api1  Created
 Container api2  Created
 Container load_balancer  Creating
 Container load_balancer  Created
Attaching to api1, api2, load_balancer, postgres
postgres       | The files belonging to this database system will be owned by user "postgres".
postgres       | This user must also own the server process.
postgres       | 
postgres       | The database cluster will be initialized with locale "en_US.utf8".
postgres       | The default database encoding has accordingly been set to "UTF8".
postgres       | The default text search configuration will be set to "english".
postgres       | 
postgres       | Data page checksums are disabled.
postgres       | 
postgres       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres       | creating subdirectories ... ok
postgres       | selecting dynamic shared memory implementation ... posix
postgres       | selecting default max_connections ... 100
postgres       | selecting default shared_buffers ... 128MB
postgres       | selecting default time zone ... Etc/UTC
postgres       | creating configuration files ... ok
postgres       | running bootstrap script ... ok
postgres       | performing post-bootstrap initialization ... ok
postgres       | initdb: warning: enabling "trust" authentication for local connections
postgres       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres       | syncing data to disk ... ok
postgres       | 
postgres       | 
postgres       | Success. You can now start the database server using:
postgres       | 
postgres       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres       | 
postgres       | waiting for server to start....2025-07-30 20:42:56.407 UTC [47] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-30 20:42:56.413 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-30 20:42:56.434 UTC [50] LOG:  database system was shut down at 2025-07-30 20:42:56 UTC
postgres       | 2025-07-30 20:42:56.447 UTC [47] LOG:  database system is ready to accept connections
postgres       |  done
postgres       | server started
postgres       | CREATE DATABASE
postgres       | 
postgres       | 
postgres       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgres       | DROP TABLE
postgres       | psql:/docker-entrypoint-initdb.d/init.sql:1: NOTICE:  table "payments" does not exist, skipping
postgres       | CREATE TABLE
postgres       | 
postgres       | 
postgres       | waiting for server to shut down...2025-07-30 20:42:57.324 UTC [47] LOG:  received fast shutdown request
postgres       | .2025-07-30 20:42:57.331 UTC [47] LOG:  aborting any active transactions
postgres       | 2025-07-30 20:42:57.402 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
postgres       | 2025-07-30 20:42:57.404 UTC [48] LOG:  shutting down
postgres       | 2025-07-30 20:42:57.411 UTC [48] LOG:  checkpoint starting: shutdown immediate
postgres       | 2025-07-30 20:42:57.587 UTC [48] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.073 s, sync=0.077 s, total=0.184 s; sync files=303, longest=0.053 s, average=0.001 s; distance=4263 kB, estimate=4263 kB; lsn=0/19140B0, redo lsn=0/19140B0
postgres       | 2025-07-30 20:42:57.594 UTC [47] LOG:  database system is shut down
postgres       |  done
postgres       | server stopped
postgres       | 
postgres       | PostgreSQL init process complete; ready for start up.
postgres       | 
postgres       | 2025-07-30 20:42:57.707 UTC [1] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-30 20:42:57.707 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres       | 2025-07-30 20:42:57.707 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres       | 2025-07-30 20:42:57.722 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-30 20:42:57.741 UTC [65] LOG:  database system was shut down at 2025-07-30 20:42:57 UTC
postgres       | 2025-07-30 20:42:57.751 UTC [1] LOG:  database system is ready to accept connections
load_balancer  | 2025/07/30 20:43:06 [error] 6#6: *4 open() "/usr/local/openresty/nginx/html/purge-payments" failed (2: No such file or directory), client: 172.20.0.1, server: , request: "POST /purge-payments HTTP/1.1", host: "localhost:9999"
[Kload_balancer exited with code 0
api2           | __  ____  __  _____   ___  __ ____  ______ 
api2           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api2           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api2           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api2           | 2025-07-30 20:44:09,566 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#41,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,567 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#49,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,602 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#45,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,602 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#37,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,566 ERROR [org.jbo.thr.errors] (executor-thread-9) Thread Thread[#44,executor-thread-9,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,605 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#40,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,606 ERROR [org.jbo.thr.errors] (executor-thread-11) Thread Thread[#46,executor-thread-11,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api2           | 2025-07-30 20:44:09,566 ERROR [org.jbo.thr.errors] (executor-thread-4) Thread Thread[#39,executor-thread-4,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api2           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api2           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api2           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api2           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api2           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api2           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api2           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api2           | 	... 14 more
api2           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api2           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api2           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api2           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api2           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api2           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api2           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api2           | 		... 26 more
api2           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api2           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api2           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api2           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api2           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api2           | 		... 32 more
api2           | 	Caused by: java.net.SocketException: Socket closed
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api2           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api2           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api2           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api2           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api2           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api2           | 		... 37 more
api2           | 
api1           | __  ____  __  _____   ___  __ ____  ______ 
api1           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api1           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api1           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api1           | 2025-07-30 20:44:09,610 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#40,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#41,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#36,executor-thread-1,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-12) Thread Thread[#47,executor-thread-12,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#45,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-14) An I/O error occurred while sending to the backend. [Error Occurred After Shutdown]
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#37,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
api1           | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
api1           | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
api1           | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
api1           | 	... 14 more
api1           | 	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: An I/O error occurred while sending to the backend.
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
api1           | 		at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:73)
api1           | 		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2454)
api1           | 		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1517)
api1           | 		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
api1           | 		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
api1           | 		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
api1           | 		... 26 more
api1           | 	Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
api1           | 		at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
api1           | 		at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
api1           | 		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:348)
api1           | 		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:70)
api1           | 		... 32 more
api1           | 	Caused by: java.net.SocketException: Socket closed
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
api1           | 		at java.base@21.0.8/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
api1           | 		at java.base@21.0.8/java.net.Socket$SocketInputStream.read(Socket.java:1099)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
api1           | 		at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
api1           | 		at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
api1           | 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
api1           | 		... 37 more
api1           | 
api1           | 2025-07-30 20:44:09,611 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#49,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
api1           | 	at org.payment.router.worker.PaymentProcessorWorker_Subclass.processPayment(Unknown Source)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:35)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: jakarta.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1283)
api1           | 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
api1           | 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
api1           | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
log truncated at line 1000
