
time="2025-07-31T10:14:27-03:00" level=warning msg="/home/rinha-user/rinha-de-backend-2025/participantes/Maxel-Uds-quarkus/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 api02 Pulling 
 api01 Pulling 
 fcce199ebec0 Already exists 
 4f4fb700ef54 Already exists 
 ec661f466405 Already exists 
 b76405cb56cd Already exists 
 3a4667a16da1 Pulling fs layer 
 af462e8499d1 Pulling fs layer 
 9b7ab51db66f Pulling fs layer 
 fcce199ebec0 Already exists 
 4f4fb700ef54 Already exists 
 ec661f466405 Already exists 
 b76405cb56cd Already exists 
 3a4667a16da1 Pulling fs layer 
 af462e8499d1 Pulling fs layer 
 9b7ab51db66f Pulling fs layer 
 af462e8499d1 Downloading [==================================================>]     102B/102B
 af462e8499d1 Verifying Checksum 
 af462e8499d1 Download complete 
 af462e8499d1 Downloading [==================================================>]     102B/102B
 af462e8499d1 Verifying Checksum 
 af462e8499d1 Download complete 
 3a4667a16da1 Verifying Checksum 
 3a4667a16da1 Download complete 
 3a4667a16da1 Downloading [==================================================>]      94B/94B
 3a4667a16da1 Download complete 
 3a4667a16da1 Extracting [==================================================>]      94B/94B
 3a4667a16da1 Extracting [==================================================>]      94B/94B
 3a4667a16da1 Extracting [==================================================>]      94B/94B
 3a4667a16da1 Extracting [==================================================>]      94B/94B
 3a4667a16da1 Pull complete 
 3a4667a16da1 Pull complete 
 af462e8499d1 Extracting [==================================================>]     102B/102B
 af462e8499d1 Extracting [==================================================>]     102B/102B
 af462e8499d1 Extracting [==================================================>]     102B/102B
 af462e8499d1 Extracting [==================================================>]     102B/102B
 af462e8499d1 Pull complete 
 af462e8499d1 Pull complete 
 9b7ab51db66f Downloading [>                                                  ]  306.3kB/30.01MB
 9b7ab51db66f Downloading [>                                                  ]  306.3kB/30.01MB
 9b7ab51db66f Downloading [=>                                                 ]  925.9kB/30.01MB
 9b7ab51db66f Downloading [=>                                                 ]  925.9kB/30.01MB
 9b7ab51db66f Downloading [===>                                               ]  1.842MB/30.01MB
 9b7ab51db66f Downloading [===>                                               ]  1.842MB/30.01MB
 9b7ab51db66f Downloading [====>                                              ]  2.465MB/30.01MB
 9b7ab51db66f Downloading [====>                                              ]  2.465MB/30.01MB
 9b7ab51db66f Downloading [=====>                                             ]  3.378MB/30.01MB
 9b7ab51db66f Downloading [=====>                                             ]  3.378MB/30.01MB
 9b7ab51db66f Downloading [======>                                            ]  3.985MB/30.01MB
 9b7ab51db66f Downloading [======>                                            ]  3.985MB/30.01MB
 9b7ab51db66f Downloading [========>                                          ]  4.898MB/30.01MB
 9b7ab51db66f Downloading [========>                                          ]  4.898MB/30.01MB
 9b7ab51db66f Downloading [=========>                                         ]  5.811MB/30.01MB
 9b7ab51db66f Downloading [=========>                                         ]  5.811MB/30.01MB
 9b7ab51db66f Downloading [===========>                                       ]  7.048MB/30.01MB
 9b7ab51db66f Downloading [===========>                                       ]  7.048MB/30.01MB
 9b7ab51db66f Downloading [=============>                                     ]  8.261MB/30.01MB
 9b7ab51db66f Downloading [=============>                                     ]  8.261MB/30.01MB
 9b7ab51db66f Downloading [===============>                                   ]  9.182MB/30.01MB
 9b7ab51db66f Downloading [===============>                                   ]  9.182MB/30.01MB
 9b7ab51db66f Downloading [=================>                                 ]  10.71MB/30.01MB
 9b7ab51db66f Downloading [=================>                                 ]  10.71MB/30.01MB
 9b7ab51db66f Downloading [===================>                               ]  11.63MB/30.01MB
 9b7ab51db66f Downloading [===================>                               ]  11.63MB/30.01MB
 9b7ab51db66f Downloading [====================>                              ]  12.54MB/30.01MB
 9b7ab51db66f Downloading [====================>                              ]  12.54MB/30.01MB
 9b7ab51db66f Downloading [======================>                            ]  13.77MB/30.01MB
 9b7ab51db66f Downloading [======================>                            ]  13.77MB/30.01MB
 9b7ab51db66f Downloading [=======================>                           ]  14.38MB/30.01MB
 9b7ab51db66f Downloading [=======================>                           ]  14.38MB/30.01MB
 9b7ab51db66f Downloading [==========================>                        ]  15.61MB/30.01MB
 9b7ab51db66f Downloading [==========================>                        ]  15.61MB/30.01MB
 9b7ab51db66f Downloading [============================>                      ]  16.83MB/30.01MB
 9b7ab51db66f Downloading [============================>                      ]  16.83MB/30.01MB
 9b7ab51db66f Downloading [==============================>                    ]  18.07MB/30.01MB
 9b7ab51db66f Downloading [==============================>                    ]  18.07MB/30.01MB
 9b7ab51db66f Downloading [===============================>                   ]  18.98MB/30.01MB
 9b7ab51db66f Downloading [===============================>                   ]  18.98MB/30.01MB
 9b7ab51db66f Downloading [================================>                  ]  19.59MB/30.01MB
 9b7ab51db66f Downloading [================================>                  ]  19.59MB/30.01MB
 9b7ab51db66f Downloading [==================================>                ]  20.51MB/30.01MB
 9b7ab51db66f Downloading [==================================>                ]  20.51MB/30.01MB
 9b7ab51db66f Downloading [====================================>              ]  21.75MB/30.01MB
 9b7ab51db66f Downloading [====================================>              ]  21.75MB/30.01MB
 9b7ab51db66f Downloading [======================================>            ]  22.99MB/30.01MB
 9b7ab51db66f Downloading [======================================>            ]  22.99MB/30.01MB
 9b7ab51db66f Downloading [========================================>          ]  24.21MB/30.01MB
 9b7ab51db66f Downloading [========================================>          ]  24.21MB/30.01MB
 9b7ab51db66f Downloading [==========================================>        ]  25.44MB/30.01MB
 9b7ab51db66f Downloading [==========================================>        ]  25.44MB/30.01MB
 9b7ab51db66f Downloading [===========================================>       ]  26.36MB/30.01MB
 9b7ab51db66f Downloading [===========================================>       ]  26.36MB/30.01MB
 9b7ab51db66f Downloading [=============================================>     ]   27.3MB/30.01MB
 9b7ab51db66f Downloading [=============================================>     ]   27.3MB/30.01MB
 9b7ab51db66f Downloading [===============================================>   ]  28.23MB/30.01MB
 9b7ab51db66f Downloading [===============================================>   ]  28.23MB/30.01MB
 9b7ab51db66f Downloading [================================================>  ]  29.15MB/30.01MB
 9b7ab51db66f Downloading [================================================>  ]  29.15MB/30.01MB
 9b7ab51db66f Verifying Checksum 
 9b7ab51db66f Verifying Checksum 
 9b7ab51db66f Download complete 
 9b7ab51db66f Download complete 
 9b7ab51db66f Extracting [>                                                  ]  327.7kB/30.01MB
 9b7ab51db66f Extracting [>                                                  ]  327.7kB/30.01MB
 9b7ab51db66f Extracting [==========>                                        ]  6.554MB/30.01MB
 9b7ab51db66f Extracting [==========>                                        ]  6.554MB/30.01MB
 9b7ab51db66f Extracting [====================>                              ]  12.45MB/30.01MB
 9b7ab51db66f Extracting [====================>                              ]  12.45MB/30.01MB
 9b7ab51db66f Extracting [==============================>                    ]  18.35MB/30.01MB
 9b7ab51db66f Extracting [==============================>                    ]  18.35MB/30.01MB
 9b7ab51db66f Extracting [=====================================>             ]  22.61MB/30.01MB
 9b7ab51db66f Extracting [=====================================>             ]  22.61MB/30.01MB
 9b7ab51db66f Extracting [==================================================>]  30.01MB/30.01MB
 9b7ab51db66f Extracting [==================================================>]  30.01MB/30.01MB
 9b7ab51db66f Pull complete 
 9b7ab51db66f Pull complete 
 api01 Pulled 
 api02 Pulled 
 Network maxel-uds-quarkus_payment-router  Creating
 Network maxel-uds-quarkus_payment-router  Created
 Container postgres  Creating
 Container postgres  Created
 Container api2  Creating
 Container api1  Creating
 Container api2  Created
 Container api1  Created
 Container load_balancer  Creating
 Container load_balancer  Created
Attaching to api1, api2, load_balancer, postgres
postgres       | The files belonging to this database system will be owned by user "postgres".
postgres       | This user must also own the server process.
postgres       | 
postgres       | The database cluster will be initialized with locale "en_US.utf8".
postgres       | The default database encoding has accordingly been set to "UTF8".
postgres       | The default text search configuration will be set to "english".
postgres       | 
postgres       | Data page checksums are disabled.
postgres       | 
postgres       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres       | creating subdirectories ... ok
postgres       | selecting dynamic shared memory implementation ... posix
postgres       | selecting default max_connections ... 100
postgres       | selecting default shared_buffers ... 128MB
postgres       | selecting default time zone ... Etc/UTC
postgres       | creating configuration files ... ok
postgres       | running bootstrap script ... ok
postgres       | performing post-bootstrap initialization ... ok
postgres       | syncing data to disk ... ok
postgres       | 
postgres       | 
postgres       | Success. You can now start the database server using:
postgres       | 
postgres       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres       | 
postgres       | initdb: warning: enabling "trust" authentication for local connections
postgres       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres       | waiting for server to start....2025-07-31 13:14:40.904 UTC [48] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-31 13:14:40.910 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-31 13:14:40.930 UTC [51] LOG:  database system was shut down at 2025-07-31 13:14:40 UTC
postgres       | 2025-07-31 13:14:40.941 UTC [48] LOG:  database system is ready to accept connections
postgres       |  done
postgres       | server started
postgres       | CREATE DATABASE
postgres       | 
postgres       | 
postgres       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgres       | DROP TABLE
postgres       | psql:/docker-entrypoint-initdb.d/init.sql:1: NOTICE:  table "payments" does not exist, skipping
postgres       | CREATE TABLE
postgres       | 
postgres       | 
postgres       | 2025-07-31 13:14:41.719 UTC [48] LOG:  received fast shutdown request
postgres       | waiting for server to shut down....2025-07-31 13:14:41.724 UTC [48] LOG:  aborting any active transactions
postgres       | 2025-07-31 13:14:41.803 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgres       | 2025-07-31 13:14:41.803 UTC [49] LOG:  shutting down
postgres       | 2025-07-31 13:14:41.808 UTC [49] LOG:  checkpoint starting: shutdown immediate
postgres       | 2025-07-31 13:14:41.930 UTC [49] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.024 s, sync=0.067 s, total=0.128 s; sync files=303, longest=0.050 s, average=0.001 s; distance=4263 kB, estimate=4263 kB; lsn=0/19140B0, redo lsn=0/19140B0
postgres       | 2025-07-31 13:14:41.937 UTC [48] LOG:  database system is shut down
postgres       |  done
postgres       | server stopped
postgres       | 
postgres       | PostgreSQL init process complete; ready for start up.
postgres       | 
postgres       | 2025-07-31 13:14:42.103 UTC [1] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-31 13:14:42.104 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres       | 2025-07-31 13:14:42.104 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres       | 2025-07-31 13:14:42.113 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-31 13:14:42.127 UTC [66] LOG:  database system was shut down at 2025-07-31 13:14:41 UTC
postgres       | 2025-07-31 13:14:42.164 UTC [1] LOG:  database system is ready to accept connections
load_balancer  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
load_balancer  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
load_balancer  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
load_balancer  | /docker-entrypoint.sh: Configuration complete; ready for start up
[Kload_balancer exited with code 0
api1           | __  ____  __  _____   ___  __ ____  ______ 
api1           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api1           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api1           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[#38,executor-thread-3,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-8) Thread Thread[#43,executor-thread-8,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | __  ____  __  _____   ___  __ ____  ______ 
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api2           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api2           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-8) Thread Thread[#43,executor-thread-8,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#41,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#41,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-15) Thread Thread[#50,executor-thread-15,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#45,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#36,executor-thread-1,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-4) Thread Thread[#39,executor-thread-4,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#49,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-7) Thread Thread[#42,executor-thread-7,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#40,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api2           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-15) Thread Thread[#50,executor-thread-15,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#36,executor-thread-1,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-12) Thread Thread[#47,executor-thread-12,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[#38,executor-thread-3,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-11) Thread Thread[#46,executor-thread-11,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-13) Thread Thread[#48,executor-thread-13,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-9) Thread Thread[#44,executor-thread-9,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#37,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-31 13:16:05,104 ERROR [org.jbo.thr.errors] (executor-thread-12) Thread Thread[#47,executor-thread-12,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-13) Thread Thread[#48,executor-thread-13,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-7) Thread Thread[#42,executor-thread-7,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#45,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#49,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,102 ERROR [org.jbo.thr.errors] (executor-thread-11) Thread Thread[#46,executor-thread-11,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#37,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,102 ERROR [org.jbo.thr.errors] (executor-thread-9) Thread Thread[#44,executor-thread-9,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api1           | 	... 13 more
api1           | 
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,105 ERROR [org.jbo.thr.errors] (executor-thread-4) Thread Thread[#39,executor-thread-4,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-31 13:16:05,103 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#40,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:39)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:32)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.8/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.8/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:37)
api2           | 	... 13 more
api2           | 
[Kapi1 exited with code 143
[Kapi2 exited with code 143
postgres       | 2025-07-31 13:16:05.965 UTC [1] LOG:  received fast shutdown request
postgres       | 2025-07-31 13:16:05.977 UTC [1] LOG:  aborting any active transactions
postgres       | 2025-07-31 13:16:05.979 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
postgres       | 2025-07-31 13:16:05.979 UTC [64] LOG:  shutting down
postgres       | 2025-07-31 13:16:05.991 UTC [64] LOG:  checkpoint starting: shutdown immediate
postgres       | 2025-07-31 13:16:06.082 UTC [64] LOG:  checkpoint complete: wrote 408 buffers (2.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.023 s, sync=0.043 s, total=0.103 s; sync files=24, longest=0.039 s, average=0.002 s; distance=4905 kB, estimate=4905 kB; lsn=0/1DDE4E8, redo lsn=0/1DDE4E8
postgres       | 2025-07-31 13:16:06.087 UTC [1] LOG:  database system is shut down
[Kpostgres exited with code 0
log truncated at line 1000
