
 Network anibalferreira-rust_backend  Creating
 Network anibalferreira-rust_backend  Created
 Container postgres  Creating
 Container redis  Creating
 Container redis  Created
 Container postgres  Created
 Container proxy  Creating
 Container proxy  Created
 Container core02  Creating
 Container core01  Creating
 Container core01  Created
 Container core02  Created
 Container haproxy  Creating
 Container haproxy  Created
Attaching to core01, core02, haproxy, postgres, proxy, redis
postgres  | The files belonging to this database system will be owned by user "postgres".
postgres  | This user must also own the server process.
postgres  | 
postgres  | The database cluster will be initialized with locale "en_US.utf8".
postgres  | The default database encoding has accordingly been set to "UTF8".
postgres  | The default text search configuration will be set to "english".
postgres  | 
postgres  | Data page checksums are disabled.
postgres  | 
postgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres  | creating subdirectories ... ok
postgres  | selecting dynamic shared memory implementation ... posix
postgres  | selecting default max_connections ... 100
postgres  | selecting default shared_buffers ... 128MB
postgres  | selecting default time zone ... Etc/UTC
postgres  | creating configuration files ... ok
postgres  | running bootstrap script ... ok
redis     | 1:C 20 Jul 2025 19:58:52.383 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis     | 1:C 20 Jul 2025 19:58:52.384 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 20 Jul 2025 19:58:52.384 * Redis version=7.4.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 20 Jul 2025 19:58:52.384 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis     | 1:M 20 Jul 2025 19:58:52.384 * monotonic clock: POSIX clock_gettime
redis     | 1:M 20 Jul 2025 19:58:52.384 * Running mode=standalone, port=6379.
redis     | 1:M 20 Jul 2025 19:58:52.385 * Server initialized
redis     | 1:M 20 Jul 2025 19:58:52.385 * Ready to accept connections tcp
proxy     | [2m2025-07-20T19:58:52.583053Z[0m [32m INFO[0m [2mactix_server::builder[0m[2m:[0m [2m310:[0m starting 1 workers
proxy     | [2m2025-07-20T19:58:52.583079Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m191:[0m Actix runtime found; starting in Actix runtime
proxy     | [2m2025-07-20T19:58:52.583084Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m197:[0m starting service: "actix-web-service-0.0.0.0:8005", workers: 1, listening on: 0.0.0.0:8005
postgres  | performing post-bootstrap initialization ... ok
postgres  | initdb: warning: enabling "trust" authentication for local connections
postgres  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres  | syncing data to disk ... ok
postgres  | 
postgres  | 
postgres  | Success. You can now start the database server using:
postgres  | 
postgres  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres  | 
postgres  | waiting for server to start....2025-07-20 19:58:53.330 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres  | 2025-07-20 19:58:53.331 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2025-07-20 19:58:53.335 UTC [51] LOG:  database system was shut down at 2025-07-20 19:58:52 UTC
postgres  | 2025-07-20 19:58:53.384 UTC [48] LOG:  database system is ready to accept connections
postgres  |  done
postgres  | server started
postgres  | 
postgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-db.sql
postgres  | CREATE TABLE
postgres  | CREATE INDEX
postgres  | 
postgres  | 
postgres  | 2025-07-20 19:58:53.590 UTC [48] LOG:  received fast shutdown request
postgres  | waiting for server to shut down....2025-07-20 19:58:53.590 UTC [48] LOG:  aborting any active transactions
postgres  | 2025-07-20 19:58:53.592 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgres  | 2025-07-20 19:58:53.602 UTC [49] LOG:  shutting down
postgres  | 2025-07-20 19:58:53.632 UTC [48] LOG:  database system is shut down
postgres  |  done
postgres  | server stopped
postgres  | 
postgres  | PostgreSQL init process complete; ready for start up.
postgres  | 
postgres  | 2025-07-20 19:58:53.826 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres  | 2025-07-20 19:58:53.826 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres  | 2025-07-20 19:58:53.826 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres  | 2025-07-20 19:58:53.827 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2025-07-20 19:58:53.829 UTC [64] LOG:  database system was shut down at 2025-07-20 19:58:53 UTC
postgres  | 2025-07-20 19:58:53.832 UTC [1] LOG:  database system is ready to accept connections
core01    | [2m2025-07-20T19:58:57.295076Z[0m [32m INFO[0m [2mcore[0m[2m:[0m [2m27:[0m Starting anibalmf1-rust server
core01    | [2m2025-07-20T19:58:57.297872Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m27:[0m Connected to Redis at redis://redis:6379
core01    | [2m2025-07-20T19:58:57.297893Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m185:[0m Connected to Redis at redis://redis:6379
core02    | [2m2025-07-20T19:58:57.402538Z[0m [32m INFO[0m [2mcore[0m[2m:[0m [2m27:[0m Starting anibalmf1-rust server
core02    | [2m2025-07-20T19:58:57.402893Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m27:[0m Connected to Redis at redis://redis:6379
core02    | [2m2025-07-20T19:58:57.402909Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m185:[0m Connected to Redis at redis://redis:6379
core01    | [2m2025-07-20T19:58:57.495571Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m99:[0m Connected to Redis at redis://redis:6379 for DLQ consumer
core01    | [2m2025-07-20T19:58:57.495595Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m200:[0m Starting to consume messages from queue: payment
core01    | [2m2025-07-20T19:58:57.495602Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m201:[0m DLQ configured as: payment_dlq
core01    | [2m2025-07-20T19:58:57.495612Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m113:[0m Starting to consume messages from DLQ: payment_dlq
core01    | [2m2025-07-20T19:58:57.496836Z[0m [32m INFO[0m [2mactix_server::builder[0m[2m:[0m [2m310:[0m starting 1 workers
core01    | [2m2025-07-20T19:58:57.498003Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m191:[0m Actix runtime found; starting in Actix runtime
core01    | [2m2025-07-20T19:58:57.498025Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m197:[0m starting service: "actix-web-service-0.0.0.0:8003", workers: 1, listening on: 0.0.0.0:8003
core02    | [2m2025-07-20T19:58:57.596231Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m99:[0m Connected to Redis at redis://redis:6379 for DLQ consumer
core02    | [2m2025-07-20T19:58:57.596371Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m200:[0m Starting to consume messages from queue: payment
core02    | [2m2025-07-20T19:58:57.596440Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m201:[0m DLQ configured as: payment_dlq
core02    | [2m2025-07-20T19:58:57.596511Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m113:[0m Starting to consume messages from DLQ: payment_dlq
core02    | [2m2025-07-20T19:58:57.596764Z[0m [32m INFO[0m [2mactix_server::builder[0m[2m:[0m [2m310:[0m starting 1 workers
core02    | [2m2025-07-20T19:58:57.596804Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m191:[0m Actix runtime found; starting in Actix runtime
core02    | [2m2025-07-20T19:58:57.596814Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m197:[0m starting service: "actix-web-service-0.0.0.0:8004", workers: 1, listening on: 0.0.0.0:8004
haproxy   | [NOTICE]   (1) : New worker (8) forked
haproxy   | [NOTICE]   (1) : Loading success.
postgres  | 2025-07-20 19:59:00.047 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | 
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
core01    | [2m2025-07-20T19:59:00.504952Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:00.505195Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:00.599915Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:00.600549Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:03.506414Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:03.506605Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:03.601982Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:03.602219Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:05.071 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core02    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
core01    | [2m2025-07-20T19:59:06.507650Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:06.507866Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:06.602934Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:06.603169Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:09.509644Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:09.509881Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:09.604285Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:09.604509Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | 
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
postgres  | 2025-07-20 19:59:10.080 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:12.511488Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:12.511715Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:12.605761Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:12.605989Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:15.091 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:15.511910Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:15.512079Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:15.607041Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:15.607313Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:18.513361Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:18.513576Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:18.607572Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:18.607782Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:20.101 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | 
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:21.514225Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:21.514522Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:21.608962Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:21.609172Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:24.515645Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:24.515904Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:24.610437Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:24.610688Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
postgres  | 2025-07-20 19:59:25.111 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:27.516943Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:27.517195Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:27.612000Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:27.612191Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | 
postgres  | 2025-07-20 19:59:30.121 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:30.518713Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:30.518892Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:30.612860Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:30.613128Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:33.520003Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:33.520197Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:33.614337Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:33.614552Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:35.130 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:36.521472Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:36.521725Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:36.615651Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:36.615895Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:39.522337Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:39.522559Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:39.617078Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:39.617315Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:40.140 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | 
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:42.523049Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:42.523270Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:42.617666Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:42.617904Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:45.150 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:45.524401Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:45.524697Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:45.618940Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:45.619138Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:48.524926Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:48.525149Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:48.620384Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:48.620575Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | 
postgres  | 2025-07-20 19:59:50.159 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:51.526424Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:51.526641Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:51.621804Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:51.622171Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T19:59:54.527848Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:54.528087Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:54.623348Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:54.623546Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 19:59:55.169 UTC [77] ERROR:  column "payment_processor" does not exist at character 8
core02    | 
core02    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core02    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T19:59:57.528967Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T19:59:57.529151Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T19:59:57.624716Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T19:59:57.624970Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
postgres  | 2025-07-20 20:00:00.181 UTC [76] ERROR:  column "payment_processor" does not exist at character 8
core01    | 
core01    | thread 'actix-rt|system:0|arbiter:0' panicked at src/store/payment.rs:162:140:
core01    | called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"payment_processor\" does not exist", detail: None, hint: None, position: Some(Original(8)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3713), routine: Some("errorMissingColumn") }) }
core01    | [2m2025-07-20T20:00:00.530362Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T20:00:00.530598Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T20:00:00.626164Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T20:00:00.626417Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core01    | [2m2025-07-20T20:00:03.531945Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core01    | [2m2025-07-20T20:00:03.532181Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
core02    | [2m2025-07-20T20:00:03.627634Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m124:[0m Checking DLQ for messages: payment_dlq
core02    | [2m2025-07-20T20:00:03.627886Z[0m [32m INFO[0m [2mcore::queue::redis[0m[2m:[0m [2m164:[0m No more messages in DLQ
haproxy   | [NOTICE]   (1) : haproxy version is 2.8.15-a9aef56
haproxy   | [WARNING]  (1) : Exiting Master process...
haproxy   | [WARNING]  (8) : Proxy web_frontend stopped (cumulated conns: FE: 13, BE: 0).
haproxy   | [WARNING]  (8) : Proxy api_servers stopped (cumulated conns: FE: 0, BE: 13).
haproxy   | [WARNING]  (1) : Current worker (8) exited with code 0 (Exit)
haproxy   | [WARNING]  (1) : All workers exited. Exiting... (0)
[Khaproxy exited with code 0
core02    | [2m2025-07-20T20:00:05.885627Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m342:[0m SIGTERM received; starting graceful shutdown
core02    | [2m2025-07-20T20:00:05.885673Z[0m [32m INFO[0m [2mactix_server::accept[0m[2m:[0m [2m143:[0m accept thread stopped
core02    | [2m2025-07-20T20:00:05.885679Z[0m [32m INFO[0m [2mactix_server::worker[0m[2m:[0m [2m593:[0m shutting down idle worker
core01    | [2m2025-07-20T20:00:05.886978Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m342:[0m SIGTERM received; starting graceful shutdown
core01    | [2m2025-07-20T20:00:05.887014Z[0m [32m INFO[0m [2mactix_server::accept[0m[2m:[0m [2m143:[0m accept thread stopped
core01    | [2m2025-07-20T20:00:05.887029Z[0m [32m INFO[0m [2mactix_server::worker[0m[2m:[0m [2m593:[0m shutting down idle worker
[Kcore02 exited with code 0
[Kcore01 exited with code 0
proxy     | [2m2025-07-20T20:00:06.887126Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m [2m342:[0m SIGTERM received; starting graceful shutdown
proxy     | [2m2025-07-20T20:00:06.887173Z[0m [32m INFO[0m [2mactix_server::worker[0m[2m:[0m [2m593:[0m shutting down idle worker
proxy     | [2m2025-07-20T20:00:06.887177Z[0m [32m INFO[0m [2mactix_server::accept[0m[2m:[0m [2m143:[0m accept thread stopped
redis     | 1:signal-handler (1753041606) Received SIGTERM scheduling shutdown...
redis     | 1:M 20 Jul 2025 20:00:06.911 * User requested shutdown...
redis     | 1:M 20 Jul 2025 20:00:06.911 * Saving the final RDB snapshot before exiting.
redis     | 1:M 20 Jul 2025 20:00:06.925 * DB saved on disk
redis     | 1:M 20 Jul 2025 20:00:06.925 # Redis is now ready to exit, bye bye...
[Kredis exited with code 0
[Kproxy exited with code 0
postgres  | 2025-07-20 20:00:07.842 UTC [1] LOG:  received fast shutdown request
postgres  | 2025-07-20 20:00:07.843 UTC [1] LOG:  aborting any active transactions
postgres  | 2025-07-20 20:00:07.847 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
postgres  | 2025-07-20 20:00:07.847 UTC [62] LOG:  shutting down
postgres  | 2025-07-20 20:00:07.883 UTC [1] LOG:  database system is shut down
[Kpostgres exited with code 0
